### ISSUE TITLE
There are problems fetching the credentials triggering a cluster scan in AKS

### ISSUE THREAD

**Issue by pavelzag** [Trolley-MGMT/trolleymgmt#51]
1. Trigger an AKS scan in Trolley.
2. The generate_kubeconfig function fails with the following:
`CompletedProcess(args='az aks get-credentials --name kubeconfig-fixes-cluster --resource-group Trolley', returncode=1, stdout='', stderr='\x1b[91mThe command failed with an unexpected error. Here is the traceback:\x1b[0m\n\x1b[91m[Errno 30] Read-only file system: \'/.kube\'\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/azure-cli/2.50.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke\n    cmd_result = self.invocation.execute(args)\n  File "/opt/homebrew/Cellar/azure-cli/2.50.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute\n    raise ex\n  File "/opt/homebrew/Cellar/azure-cli/2.50.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially\n    results.append(self._run_job(expanded_arg, cmd_copy))\n  File "/opt/homebrew/Cellar/azure-cli/2.50.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job\n    result = cmd_copy(params)\n  File "/opt/homebrew/Cellar/azure-cli/2.50.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__\n    return self.handler(*args, **kwargs)\n  File "/opt/homebrew/Cellar/azure-cli/2.50.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler\n    return op(**command_args)\n  File "/opt/homebrew/Cellar/azure-cli/2.50.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/acs/custom.py", line 1161, in aks_get_credentials\n    _print_or_merge_credentials(\n  File "/opt/homebrew/Cellar/azure-cli/2.50.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/acs/custom.py", line 1279, in _print_or_merge_credentials\n    os.makedirs(directory)\n  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/os.py", line 225, in makedirs\n    mkdir(name, mode)\nOSError: [Errno 30] Read-only file system: \'/.kube\'\x1b[0m\nTo check existing issues, please visit: https://github.com/Azure/azure-cli/issues\n')`

**Comment by pavelzag** [comment]
Fixed
